name: auto_monthly_recommend

on:
  schedule:
  # TODO: for test 每十分钟执行一次
  - cron: "*/10 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build-go
        run: |
          go env -w GO111MODULE=on
          cd actions && go build -o monthly monthly.go
      - name: create-issue
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: cd actions &&./monthly -c ./issuesinfo.json
